
FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer


RUN useradd -G www-data,root -u 1000 -d /home/user user
WORKDIR /var/www
COPY . .


RUN chown -R user:user /var/www


USER user


RUN composer install


EXPOSE 9000


CMD ["php-fpm"]