version: '3'

services:
  php:
    build:
      context: .
      dockerfile: DockerFile  # Assurez-vous que le nom est correct
    volumes:
      - .:/var/www
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data: