# Dockerfile pour Symfony
FROM php:8.2-fpm

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Créer un utilisateur non privilégié
RUN useradd -G www-data,root -u 1000 -d /home/user user
WORKDIR /var/www
COPY . .

# Changer le propriétaire des fichiers
RUN chown -R user:user /var/www

# Passer à l'utilisateur non privilégié
USER user

# Installer les dépendances PHP
RUN composer install

# Exposer le port 9000
EXPOSE 9000

# Démarrer le serveur PHP
CMD ["php-fpm"]